[package]
name = "starboard"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
auto-const-array = "0.2.2"
bincode = "2.0.1"
chrono = "0.4.45"
clap = "4.6.1"
crossterm = "0.29.0"
ctrlc = "3.5.2"
evdev = "0.13.2"
heapless = "0.9.3"
libc = "0.2.189"
ratatui = "0.30.1"
tokio = { version = "1.52.3", features = ["full"] }
tokio-util = "0.7.18"

[features]
debug = []
server = []
client = []
dummy-steam-deck = []
loopback = []

[profile.dev]
debug = true
strip = false
